# Generated by Django 4.1.2 on 2022-10-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(verbose_name='Kilometrage')),
                ('desc', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('cost', models.FloatField(verbose_name='Costo')),
                ('date', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.car', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
