# Generated by Django 4.1.2 on 2022-10-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_car_brand_car_car_alter_car_id'),
        ('management', '0004_alter_management_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Auto'),
        ),
    ]
